### ISSUE TITLE
Email account information written in plain text 

### ISSUE THREAD

**Issue by s1155026040** [ierg4210/shop03#1]
The owner's email account and password are written in plain text in the github resource. Thus I can guess one of the account for shop03 is that email account. I use that to do the 'forget password' action and an email has been sent to the account. Having the password, I can login to the email and change the password. Then I can login to the shop. What's more, I can see all emails of the owner.:) I didn't enter his/her email thus not taking any further action yet. But if the account is admin, I can change all database data. 
![1](https://cloud.githubusercontent.com/assets/10612324/7517999/dc2dd0c6-f50a-11e4-8a8e-81b78558193f.png)
![2](https://cloud.githubusercontent.com/assets/10612324/7518100/8c6bb868-f50b-11e4-8942-7336f9982932.png)

**Comment by s1155002037** [comment]
Thanks for reporting this issue. But Adon said attacking with knowledge of the confidential information like password on Github is not counted. Since even I delete the information, unless I delete the whole repo, you can still found it on the commit history.
