### ISSUE TITLE
Potential MITM attack

### ISSUE THREAD

**Issue by s1155016069** [ierg4210/shop03#2]
Detailed steps to reproduce? (e.g., visit /admin2 without login)
visit shop03 admin login using http
2. What did you see? (e.g., led to a page that can delete a product)
it doesn't redirect to https
3. What did you expect to see? (e.g., admin actions require authentication)
it will redirect to https
4. What is the possible fix? (e.g., delete the sample/testing page)
redirect to https to avoid MITM attack
![shop03](https://cloud.githubusercontent.com/assets/10684896/7530255/af1bdc28-f577-11e4-99e3-21b95cc9ce0e.jpg)

**Comment by s1155002037** [comment]
Thanks for reporting this issue. Even though the index page of admin is not using https, actually the form handling and others are using https. So no MITM attack can be successful. You can have a try. Anyway I rewrite it to avoid further misunderstanding.
